//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomCityGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomCityGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to les Escaldes	42.50729	1.53414	AD
        ///Andorra la Vella	42.50779	1.52109	AD
        ///Umm al Qaywayn	25.56473	55.55517	AE
        ///Ras al-Khaimah	25.78953	55.9432	AE
        ///Khawr Fakkān	25.33132	56.34199	AE
        ///Dubai	25.0657	55.17128	AE
        ///Dibba Al-Fujairah	25.59246	56.26176	AE
        ///Dibba Al-Hisn	25.61955	56.27291	AE
        ///Sharjah	25.33737	55.41206	AE
        ///Ar Ruways	24.11028	52.73056	AE
        ///Al Fujayrah	25.11641	56.34141	AE
        ///Al Ain	24.19167	55.76056	AE
        ///Ajman	25.41111	55.43504	AE
        ///Adh Dhayd	25.28812	55.88157	AE
        ///Abu Dhabi	24.46667	54.36667	AE
        ///Zaranj	30.95 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string simplifiedcities15000 {
            get {
                return ResourceManager.GetString("simplifiedcities15000", resourceCulture);
            }
        }
    }
}
